<?php
$title = 'Delete User Tag';
$this->headTitle($title);
?>
<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs">
		<a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a>
		<div class="breadcrumb_divider"></div>
		<a href="<?php echo $this->url('admin/admin-user-tags') ?>">Manage User Tags</a>
		<div class="breadcrumb_divider"></div>
		<a href="javascript:void(0);">Delete User </a>
		</article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
<article class="module width_full">
			<header><h3><?php echo $this->escapeHtml($title); ?></h3></header>
				<div class="module_content">
<p>Are you sure that you want to delete '<?php echo $this->escapeHtml($userTag->tag_title); ?>' of user <?php echo $this->escapeHtml($userTag->user_first_name); ?> <?php echo $this->escapeHtml($userTag->user_last_name); ?></p>
<?php 
$url = $this->url('admin/admin-user-tags', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$userTag->user_tag_id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
				</div>
		</article>
    
    <div class="clear"></div>
    <div class="spacer"></div>
</section> 