<?php
// module/User/view/user/user/add.phtml:
$this->headTitle($this->translate('Login'));
?>

<!--flash Messages.Stored in session-->
<?php if(isset($flashMessages) && count($flashMessages)) : ?>
<ul class="session">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--error Message-->
<?php if(isset($error) && count($error)) : ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--success message-->
<?php if(isset($success) && count($success)) : ?>
<ul class="success">
    <?php foreach ($success as $successmsg) : ?>
    <li><?php echo $successmsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<div class="header-inner">
	<div class="login-form">
<?php
$form = $this->form;
$url = $this->url()."/$key/$id"; 
$form->setAttribute('action', $url);
//$form->prepare();
?>
<?php echo $this->form()->openTag($form);?>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('csrf'));?>
	</div>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('user_password'));?>
	</div>
	<div class="input-outer">
		<?php echo $this->formRow($form->get('user_retype_password'));?>
	</div>
	<div class="signup-field">
			<?php echo $this->formRow($form->get('submit'));?>			 
		</div>
<?php echo $this->form()->closeTag();?>
	</div>
</div>