<?php
$title = 'Galaxy';
$this->headTitle($title);
?>
<section id="secondary_bar">            
	<div class="breadcrumbs_container">
		<article class="breadcrumbs"><a href="<?php echo $this->url('jadmin') ?>">Admin Dashboard </a><div class="breadcrumb_divider"></div>  <a  class="current" href="<?php echo $this->url('jadmin/admin-galaxy') ?>">Manage Galaxy</a></article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
	<article class="module width_3_quarter">
		<header><h3 class="tabs_involved"><?php echo $this->escapeHtml($title); ?></h3>
			<ul class="tabs">
				<li><a href="<?php echo $this->url('jadmin/admin-galaxy-add'); ?>">Add New Galaxy</a></li>
			</ul>
		</header>
		<div class="tag_quick_search">
			<form  method="post" action="<?php echo $this->url('jadmin/admin-galaxy');?>">
				<input type="text" id="galexy_search" name="galexy_search" value="<?php echo $search; ?>" />
				<input type="submit" value="Search" />
			</form>
		</div>
		<div>Page <?php echo $page  ?> out of <?php echo $total_pages; ?> page</div>
		<div class="tab_container">
			<div id="tab1" class="tab_content">
			
				<table class="tablesorter" cellspacing="0"> 
					<thead> 
						<tr>                         
							<th>#</th> 
							<th>
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=> $page,'sort'=>'title','order'=>($field=='title'&&$order=='ASC')?'desc':'asc','search'=>$search));?>">
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=> $page,'sort'=>'title','order'=>($field=='title'&&$order=='ASC')?'desc':'asc'));?>">
							<?php } ?>Galaxy Title
							</a></th> 
							<th>
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=> $page,'sort'=>'seotitle','order'=>($field=='seotitle'&&$order=='ASC')?'desc':'asc','search'=>$search));?>">
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=> $page,'sort'=>'seotitle','order'=>($field=='seotitle'&&$order=='ASC')?'desc':'asc'));?>">
							<?php } ?>Galaxy SEO Title
							</a></th> 
							<th>Actions</th> 
						</tr> 
					</thead> 
					<tbody> 
						<?php 
							$i=0;
						foreach ($allGroupData as $group) :
						$i++;
                        ?>
                        <tr>                            
                            <td><?php echo $this->escapeHtml($i); ?></td> 
                            <td><?php echo $this->escapeHtml($group->group_title); ?> <?php if($group->group_count>0){ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>$group->group_seo_title,'page'=>1,'sort'=>'title','order'=>'asc'));?>">
							 <?php echo "($group->group_count)";} ?></a> </td> 
                            <td><?php echo $this->escapeHtml($group->group_seo_title); ?></td> 
                            <td><a href="<?php echo $this->url('jadmin/admin-galaxy-edit', array('id' => $group->group_id));
                            ?>"><img src="<?php echo $this->basePath(); ?>/public/images/edit.png" title="Edit"></a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('jadmin/admin-galaxy-delete', array( 'id' => $group->group_id));
        ?>"><img src="<?php echo $this->basePath(); ?>/public/images/trash.png" title="Trash"></a></td> 
                        </tr> 
						<?php endforeach; ?> 
						<tr>
						<td colspan="3">
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Next &raquo;</a>
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order)));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>1,'sort'=>$field,'order'=>strtolower($order)));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-galaxy',    array('page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Next &raquo;</a>
							<?php } ?>
						</td>
					</tr>
					</tbody> 
				</table>
			</div><!-- end of #tab1 -->
		</div><!-- end of .tab_container -->
	</article><!-- end of content manager article -->
	<div class="clear"></div>
	<div class="spacer"></div>
</section>