<?php
$title = 'Add new Country';
$this->headTitle($title);
?>
<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs">
		<a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a>
		<div class="breadcrumb_divider"></div>  
		<a href="<?php echo $this->url('admin/admin-country') ?>">Manage Countries</a>
		<div class="breadcrumb_divider"></div>
		<a class="current" href="javascript:void(0);">Add Country </a></article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
   
    <article class="module width_full">
        <header>
		<h3><?php echo $this->escapeHtml($title); ?></h3>
		</header>
        <?php
        $form = $this->form;
		$form->setAttribute('action', $this->url('admin/admin-country', array('action' => 'add')));
		$form->prepare();

        echo $this->form()->openTag($form) . PHP_EOL;

        echo $this->formHidden($form->get('country_id')) . PHP_EOL;
		echo $this->formHidden($form->get('country_status')) . PHP_EOL;

        ?>
        <div class="module_content">
         
            <fieldset>
                <label>Name*</label>
                <?php echo $this->formRow($form->get('country_title')) . PHP_EOL; ?>
            </fieldset>
            <fieldset> <!-- to make two field float next to one another, adjust values accordingly -->
                <label>Country ISO Code*</label>
                <?php echo $this->formRow($form->get('country_code')) . PHP_EOL; ?>
            </fieldset>
           

            <div class="clear"></div>
        </div>
        <footer>
            <div class="submit_link">
                <?php echo $this->formInput($form->get('submit')) . PHP_EOL; ?>

            </div>
        </footer>


        <?php echo $this->form()->closeTag($form) . PHP_EOL; ?>
    </article><!-- end of post new article -->


    <div class="clear"></div>
    <div class="spacer"></div>


</section>