<?php
$title = 'Delete Country';
$this->headTitle($title);
?>
<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs">
		<a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a>
		<div class="breadcrumb_divider"></div>  
		<a href="<?php echo $this->url('admin/admin-country') ?>">Manage Countries</a>
		<div class="breadcrumb_divider"></div>  
		<a  class="current" href="javascript:void(0);">Delete</a>
		</article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
<article class="module width_full">
			<header><h3><?php echo $this->escapeHtml($title); ?></h3></header>
				<div class="module_content">
				
<?php if(isset($usersList) && count($usersList)) : ?>
		<p>You can not delete County  <b>'<?php echo $this->escapeHtml($country->country_title); ?>'</b>, Users are register using this Country</p>
		<?php 
	$url = $this->url('admin/admin-country', array('action' => 'delete', 'id'=>$this->id)); ?>
	<form action="<?php echo $url; ?>" method="post">
	<div>
	  <input type="hidden" name="id" value="<?php echo (int)$country->country_id; ?>" />
	   
	  <input type="submit" name="del" value="Back" />
	</div>
	</form>
		
<?php else : ?>
	<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHtml($country->country_title); ?>', Country Code '<?php echo $this->escapeHtml($country->country_code); ?>'?
</p>
<?php 
$url = $this->url('admin/admin-country', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$country->country_id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
<?php endif; ?>

				</div>
		</article>
    
    <div class="clear"></div>
    <div class="spacer"></div>
</section>