<?php 
$title = 'Countries';
$this->headTitle($title); ?>
<?php $url_order = 'ASC';  // the following lines
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>

<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs"><a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a><div class="breadcrumb_divider"></div>  <a class="current" href="<?php echo $this->url('admin/admin-country') ?>">Manage Countries</a></article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">

    <article class="module width_3_quarter">
        <header><h3 class="tabs_involved"><?php echo $this->escapeHtml($title); ?></h3>
            <ul class="tabs">
				<li><a href="<?php echo $this->url('admin/admin-country', array('action'=>'add'));?>">Add New Country</a></li>
            </ul>
        </header>

        <div class="tab_container">
            <div id="tab1" class="tab_content">
                <table class="tablesorter" cellspacing="0"> 
                    <thead> 
                        <tr> 
                            <th></th> 
                            <th>Id</th>
							<th>Country Name</th>
							<th>Country Code</th>
							<th>Actions</th>
                        </tr> 
                    </thead> 
                    <tbody> 
                      <?php foreach($allCountryData as $country) : ?>
                            <tr> 
                                <td><input type="checkbox"></td> 
                                <td><?php echo $this->escapeHtml($country->country_id);?></td>
								<td><?php echo $this->escapeHtml($country->country_title);?></td>
								<td><?php echo $this->escapeHtml($country->country_code);?></td>
                                <td><a href="<?php echo $this->url('admin/admin-country',
            array('action'=>'edit', 'id' => $country->country_id));?>"><img src="<?php echo $this->basePath(); ?>/images/icn_edit.png" title="Edit"></a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('admin/admin-country',
            array('action'=>'delete', 'id' => $country->country_id));?>"><img src="<?php echo $this->basePath(); ?>/images/icn_trash.png" title="Trash"></a></td> 
                            </tr> 
                        <?php endforeach; ?> 
                    </tbody> 
                </table>
            </div><!-- end of #tab1 -->

        </div><!-- end of .tab_container -->

    </article><!-- end of content manager article -->
    <div class="clear"></div>
    <div class="spacer"></div>


</section>