				<?php
				$i=0;
				foreach($usersWithMessagesData as $messages){ 
				$i++;
				?>
				<div class="msg-list-outer" id="msg-list-outer<?php echo $messages->message_user; ?>">
					<div class="msg-user-info">
						<div class="messager-img">
						<a href="javascript:void(0)" id="<?php echo $messages->message_user; ?>" class="listMessage">
							<?php if($messages->profile_photo!=''){ ?>
						<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $messages->user_id ?>/66x66/<?php echo $messages->profile_photo; ?>" alt="" />
						<?php }else if($messages->user_register_type == 'facebook' && $messages->user_fbid!=''){ ?>
							<img src="https://graph.facebook.com/<?php echo $messages->user_fbid; ?>/picture?width=66&&height=66" />
						<?php }else{ ?>
						<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
						<?php } ?>
						</a>
						</div>
						<div class="messager-name"><?php echo $messages->user_given_name ; ?></div>
						<div class="delete-msg">							 
							<span class="unread"></span>
							<div class="msg-date">
								<a href="javascript:void(0)" id="<?php echo $messages->message_user; ?>" class="listMessage">
							<?php echo date("d/m/Y",strtotime($messages->user_message_added_timestamp)); ?>
							</a>
							</div>
						</div>
						<div class="clear"></div>
					</div>
					<div class="msg-short"><a href="javascript:void(0)" id="<?php echo $messages->message_user; ?>" class="listMessage"><?php echo substr($messages->user_message_content,0,50) ?> ...</a></div>
					
				</div>
				<?php } ?>
				<?php if($i==0){ ?>
					<script>
						userload = 1;
					</script>
				<?php } ?>
				 