
<?php if(!empty($error)){ ?>
	<ul>
	<?php foreach($error as $er){ ?>
		<li><?php echo $er; ?> </li>
	<?php } ?>
	</ul>
<?php } 
 
 if(isset($userMessagesData)&&!empty($userMessagesData)){
	$i= 0;
	  $i++;?>
		<div class="message-container<?php if($i%2==0){ echo " msg-alternate";} ?>"  id="message-container_<?php echo $userMessagesData['message'][0]['user_message_id']; ?>">
			<div class="message-image">
			<div class="message_select" >
			<input type="checkbox" class="mesg_chk" id="<?php echo $userMessagesData['message'][0]['user_message_id']; ?>" value="<?php echo $userMessagesData['message'][0]['user_message_id']; ?>"  name="message_id[]" />
            <label for="<?php echo $userMessagesData['message'][0]['user_message_id']; ?>"><span></span></label>
			</div>
				 <a href="<?php echo $this->url('memberprofile',array('member_profile'=>$userMessagesData['message'][0]['user_profile_name'])) ?>" class="profile-img-link">
				<?php if($userMessagesData['message'][0]['profile_photo']!=''){ ?>
				<img src="<?php echo $this->basePath(); ?>/public/datagd/profile/<?php echo $userMessagesData['message'][0]['user_id'] ?>/66x66/<?php echo $userMessagesData['message'][0]['profile_photo']; ?>" alt="" />
				<?php }else if($userMessagesData['message'][0]['user_register_type'] == 'facebook' && $userMessagesData['message'][0]['user_fbid']!=''){ ?>
					<img src="https://graph.facebook.com/<?php echo $userMessagesData['message'][0]['user_fbid']; ?>/picture?width=66&&height=66" />
				<?php }else{ ?>
				<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />
				<?php } ?>
				</a>
			</div>
			<div class="main-msg">
				<div class="msgr-name">
					<a href="<?php echo $this->url('memberprofile',array('member_profile'=>$userMessagesData['message'][0]['user_profile_name'])) ?>" class="profile-img-link"><?php echo $userMessagesData['message'][0]['user_given_name']; ?></a>
					<span><?php echo $userMessagesData['message'][0]['user_message_added_timestamp']; ?></span>
					<div class="clear"></div>
				</div>
				<div class="msg-text">
					 <?php echo $userMessagesData['message'][0]['user_message_content']; ?> 	
					 <?php foreach($userMessagesData['message_attachments'] as $attachments){
						if($attachments['attachment_type']=='image'){
					 ?>
					 <img src="<?php echo $this->basePath()."/public/datagd/message/".$attachments['attachment_element']; ?>" width="250px"/>
					<?php }else{
					?>	
					<a href="<?php echo $this->basePath()."/public/datagd/message/".$attachments['attachment_element']; ?>"><?php echo $attachments['attachment_element']; ?></a>
					 <?php } } ?>
				</div>
				
			</div>
			<div class="clear"></div>
		</div>
	
		<div class="clear"></div>
	  <?php } ?>