<?php 
	if(isset($error)&&!empty($error)){
		echo "<ul>";
		foreach($error as $list){
			echo "<li>".$list."</li>";
		}
		echo "</ul>";
	}else{
?>		
	<?php 
		$i=0;
	foreach($users as $list){$i++;
		?>
		<a id="user_list_<?php echo $list->user_id; ?>" href="javascript:void(0)" class="user_list"><?php echo $list->user_first_name." ".$list->user_last_name; ?></a>
	<?php 
	}
	if($i == 0){
		echo "No more users are available";
	}else{
		echo '<a href="javascript:void(0)" id="owners_loadmore" class="owners_loadmore">Load more </a>';
	}
		?>
<?php 	} ?>
