<?php
$title = 'Delete Planet Suggestion';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
	<a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a> >> 
	<a href="<?php echo $this->url('admin/admin-planet', array('action'=>'approvelist')) ?>">Manage Planet Approval</a> >>
	<a href="javascript:void(0);">Delete Planet Suggestion</a>
</div><br />
<!--flash Messages.Stored in session-->
<?php if(isset($flashMessages) && count($flashMessages)) : ?>
<ul class="session">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--error Message-->
<?php if(isset($error) && count($error)) : ?>
<ul class="error">
    <?php foreach ($error as $errormsg) : ?>
    <li><?php echo $errormsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<!--success message-->
<?php if(isset($success) && count($success)) : ?>
<ul class="success">
    <?php foreach ($success as $successmsg) : ?>
    <li><?php echo $successmsg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<p>Are you sure that you want to delete '<b><?php echo $this->escapeHtml($approvegroup->group_add_suggestion_name); ?></b>'
</p>
<?php 
$url = $this->url('admin/admin-planet', array('action' => 'deletesuggestplanet', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$approvegroup->group_add_suggestion_id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
 


 
