<?php
$title = 'Planet';
$this->headTitle($title);
$this->HeadScript()->appendFile($this->basePath().'/public/js/admin_planet_approve.js','text/javascript');
?>
<section id="secondary_bar">
    <div class="breadcrumbs_container">
        <article class="breadcrumbs"><a href="<?php echo $this->url('jadmin') ?>">Admin Dashboard </a><div class="breadcrumb_divider"></div>  <a  class="current" href="<?php echo $this->url('jadmin/admin-planet') ?>">Manage Planet</a></article>
    </div>
</section>
<section id="main" class="column">
    <article class="module width_3_quarter">
        <header><h3 class="tabs_involved"><?php echo $this->escapeHtml($title); ?></h3>
            <ul class="tabs">
				<li class="active"><a href="#tab1">List All</a></li>
                <li class="second"><a href="<?php echo $this->url('jadmin/admin-planet-add'); ?>">Add New Planet</a></li>
				<li><a href="<?php echo $this->url('jadmin/admin-planet-approvelist', array('action'=>'approvelist'));?>">Approve Planets added by Users</a></li>
            </ul>
        </header>
		<div class="tag_quick_search">
			<form  method="post" action="<?php echo $this->url('jadmin/admin-planet');?>">
				<input type="text" id="planet_search" name="planet_search" value="<?php echo $search; ?>" />
				<input type="submit" value="Search" />
			</form>
		</div>
		<div>Page <?php echo $page  ?> out of <?php echo $total_pages; ?> page</div>
        <div class="tab_container">
            <div id="tab1" class="tab_content">
                <table class="tablesorter" cellspacing="0"> 
                    <thead> 
                        <tr>                              
                            <th>#</th>                              
                            <th>
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=> $page,'sort'=>'title','order'=>($field=='title'&&$order=='ASC')?'desc':'asc','search'=>$search));?>">
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=> $page,'sort'=>'title','order'=>($field=='title'&&$order=='ASC')?'desc':'asc'));?>">
							<?php } ?>
							Planet
							</a></th> 
							<th><?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=> $page,'sort'=>'galexy','order'=>($field=='galexy'&&$order=='ASC')?'desc':'asc','search'=>$search));?>">
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=> $page,'sort'=>'galexy','order'=>($field=='galexy'&&$order=='ASC')?'desc':'asc'));?>">
							<?php } ?>Galaxy</a></th> 
                            <th>Actions</th> 
                        </tr> 
                    </thead> 
                    <tbody> 
                        <?php 
						$i=($page==1)?0:$page-1;
						$i = $i*20;
						foreach ($allSubGroupData as $group) :
						$i++;
                            ?>
                            <tr>                                 
                                <td><?php echo $this->escapeHtml($i); ?></td>                                  
                                <td><?php echo $this->escapeHtml($group->group_title); ?><?php if($group->member_count){ ?><a href="">(<?php echo $group->member_count; ?> members)</a><?php } ?><?php if($group->activity_count){ ?><a href="">(<?php echo $group->activity_count; ?> activities)</a><?php } ?></td> 
								<td><?php echo $this->escapeHtml($group->parent_title); ?></td> 
                                <td><a href="<?php echo $this->url('jadmin/admin-planet-view', array('id' => $group->group_id));
                        ?>"><img src="<?php echo $this->basePath(); ?>/public/images/view.png" title="Edit"></a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('jadmin/admin-planet-edit', array('id' => $group->group_id));
                        ?>"><img src="<?php echo $this->basePath(); ?>/public/images/edit.png" title="Edit"></a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('jadmin/admin-planet-delete', array('action' => 'delete', 'id' => $group->group_id));
                            ?>"><img src="<?php echo $this->basePath(); ?>/public/images/trash.png" title="Trash"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('jadmin/admin-planet-approve', array('action' => 'approve', 'planet_id' => $group->group_id));
                            ?>" class="planet_approve" id="planet_approve_<?php echo $group->group_id; ?>"><?php if($group->group_status){ ?>
							<img src="<?php echo $this->basePath(); ?>/public/images/tick.png" title="planet_approve"></a>
							<?php }else{ ?>
								<img src="<?php echo $this->basePath(); ?>/public/images/red-alert.png" title="planet_approve"></a>
							<?php } ?></a>
							
							</td> 
                            </tr> 
                        <?php endforeach; ?> 
						<tr>
						<td colspan="3">
							<?php if($search!=''){ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>1,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order),'search'=>$search));?>">Next &raquo;</a>
							<?php }else{ ?>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>(($page-1)>0)?$page-1:1,'sort'=>$field,'order'=>strtolower($order)));?>">&laquo; Prev</a>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>1,'sort'=>$field,'order'=>strtolower($order)));?>">Frist</a>
							<span> <?php echo $page; ?> </span>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Last</a>
							<a href="<?php echo $this->url('jadmin/admin-planet',    array('galaxy'=>($galaxy!='')?$galaxy:'All','page'=>(($page+1)<=$total_pages)?$page+1:$total_pages,'sort'=>$field,'order'=>strtolower($order)));?>">Next &raquo;</a>
							<?php } ?>
						</td>
					</tr>
                    </tbody> 
                </table>
            </div>
        </div>
    </article>
    <div class="clear"></div>
    <div class="spacer"></div>
</section>