<?php
$this->headTitle($title);
?>


<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs"><a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a><div class="breadcrumb_divider"></div>  <a  class="current" href="<?php echo $this->url('admin/admin-notification') ?>"><?php echo $title;?></a></article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
<!---->


<?php if(count($flashMessages)) : ?>
    <h4 class="<?php echo $flashMessages[0]['type'];?>"><?php echo $flashMessages[0]['message'];?></h4>
<?php endif; ?>
    <article class="module width_3_quarter">
        <header><h3 class="tabs_involved"><?php echo $this->escapeHtml($title); ?></h3> 
		<ul class="tabs">
   			<li class="active"><a href="#tab1">List All</a></li>
    		<li><a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'add'));?>">Add New</a></li>
		</ul>
        </header>

        <div class="tab_container">
            <div id="tab1" class="tab_content">
                <table class="tablesorter" cellspacing="0"> 
                    <thead> 
                        <tr>
						<th></th>
						<th>Id</th>
						<th>Notification Title</th>
						<th>Notification Description</th>
						<th>Notification Status</th>
						<th>Actions</th>
						</tr>
                    </thead> 
                    <tbody> 
                        <?php foreach($all_notification_types as $rows) : 
						
						$status = 'Enabled';
						
						if($rows->notification_type_status == 0) {
						$status = 'Disabled';
						}elseif($rows->notification_type_status == 1) {
						$status = 'Enabled';
						}
						else{
						$status = $status; 
						}
						
						?>
                            <tr> 
                                <td><input type="checkbox"></td> 
                                <td><?php echo $this->escapeHtml($rows->notification_type_id);?></td>
								<td><?php echo $this->escapeHtml($rows->notification_type_title);?></td>
								<td><?php echo substr($this->escapeHtml($rows->notification_type_discription),0,30); if(strlen($this->escapeHtml($rows->notification_type_discription)) >  30) {echo ' ...';}?></td>
								<td><span class="<?php echo "status_".$status; ?>"><?php echo $status;?></span></td>
									
								<td>
									<a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'view', 'id' => $rows->notification_type_id));?>"><img src="<?php echo $this->basePath(); ?>/images/icn_search.png" title="view"></a>
									&nbsp;&nbsp;&nbsp;&nbsp;
									<a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'edit', 'id' => $rows->notification_type_id));?>"><img src="<?php echo $this->basePath(); ?>/images/icn_edit.png" title="Edit"></a>	
										&nbsp;&nbsp;&nbsp;&nbsp;
										<?php if($rows->notification_type_status != 1) { ?>
									<a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'enable', 'id' => $rows->notification_type_id));?>"><img src="<?php echo $this->basePath(); ?>/images/bullet-green.png" title="Enable"></a>
										<?php } else{ ?>
									<a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'disable', 'id' => $rows->notification_type_id));?>"><img src="<?php echo $this->basePath(); ?>/images/bullet-red.png" title="Disable"></a>	
										<?php } ?>
										&nbsp;&nbsp;&nbsp;&nbsp;
									<a href="<?php echo $this->url('admin/admin-notification',
										array('action'=>'delete', 'id' => $rows->notification_type_id));?>"  onClick="return confirm('Are you sure to DELETE this Notification type ?')"><img src="<?php echo $this->basePath(); ?>/images/icn_trash.png" title="Trash"></a>
								</td>
							</tr> 
                        <?php endforeach; ?> 
                    </tbody> 
                </table>
            </div><!-- end of #tab1 -->

        </div><!-- end of .tab_container -->

    </article><!-- end of content manager article -->
    <div class="clear"></div>
    <div class="spacer"></div>


</section>




