<?php
$title = 'Delete Tag';
$this->headTitle($title);
?>
<section id="secondary_bar">

    <div class="breadcrumbs_container">
        <article class="breadcrumbs">
		<a href="<?php echo $this->url('admin') ?>">Admin Dashboard </a>
		<div class="breadcrumb_divider"></div>
		<a href="<?php echo $this->url('admin/admin-planet-tags') ?>">Manage Planet Tags</a>
		<div class="breadcrumb_divider"></div>
		<a class="current" href="javascript:void(0);">Delete</a>
		</article>
    </div>
</section><!-- end of secondary bar -->
<section id="main" class="column">
<article class="module width_full">
			<header><h3><?php echo $this->escapeHtml($title); ?></h3></header>
				<div class="module_content">
					<p>Are you sure that you want to delete tag '<?php echo $this->escapeHtml($groupTag->tag_title); ?>' from Planet '<?php echo $this->escapeHtml($groupTag->group_title); ?>' ?
					</p>
					<?php 
					$url = $this->url('admin/admin-planet-tags', array('action' => 'delete', 'id'=>$this->id)); ?>
					<form action="<?php echo $url; ?>" method="post">
					<div>
					  <input type="hidden" name="id" value="<?php echo (int)$groupTag->group_tag_id; ?>" />
					  <input type="submit" name="del" value="Yes" />
					  <input type="submit" name="del" value="No" />
					</div>
					</form>
 
				</div>
		</article>
    
    <div class="clear"></div>
    <div class="spacer"></div>
</section>




=============================================================================


 



 
