<div class="userdetails"><a href="<?php //echo $this->url('profile') ?>"><?php echo $userData->user_given_name?></a></div>
<div class="clear"></div>
<div class="planet_suggestions">Planet suggestions comes here</div>
<div class="outermain">
	<div class="left_container">
		<ul>
			<li><a href="<?php echo $this->url('groups') ?>">Galaxies</a></li>
			<li><a href="">Connections</a></li>
			<li><a href="">Messages</a></li>
			<li><a href="">Notifications</a></li>
		</ul>
	</div>
	<div class="main_feeds">
		feeds comes here
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
	</div>
	<div class="right_container">
		right side bar
		<br />
		<br /><br />
		<br />
		<br />
		<br />
		
	</div>
	
</div>
<div class="clear"></div>